apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: nodejs-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
            - name: followers-volume
              mountPath: /app/followers
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: followers-volume
          persistentVolumeClaim:
            claimName: followers-pvc
