apiVersion: v1
kind: PersistentVolume
metadata:
  name: followers-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/followers
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: followers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
