apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `pfc-bbdd`;
    USE `pfc-bbdd`;
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";

    -- Drop tables in reverse order of dependency
    DROP TABLE IF EXISTS `publicacion_tag`;
    DROP TABLE IF EXISTS `tag`;
    DROP TABLE IF EXISTS `publicacion`;
    DROP TABLE IF EXISTS `usuario`;

    -- Create usuario table
    CREATE TABLE `usuario` (
      `id` int(10) NOT NULL AUTO_INCREMENT,
      `nombre` varchar(30) NOT NULL,
      `email` varchar(50) NOT NULL,
      `password` varchar(100) NOT NULL,
      `foto_perfil` varchar(255) NOT NULL DEFAULT '',
      `foto_banner` varchar(255) NOT NULL DEFAULT '',
      `NPublicaciones` int NOT NULL DEFAULT 0,
      `primera_vez` tinyint(1) NOT NULL DEFAULT 1,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Insert sample users
    INSERT INTO `usuario` (`id`, `nombre`, `email`, `password`, `foto_perfil`, `foto_banner`, `NPublicaciones`, `primera_vez`) VALUES
    (1, 'Isaac', 'sdaniel9391@gmail.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '', '', 1, 1),
    (2, 'Pandorito', 'leandroutz@gmail.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', './img/perfil/perfil_default.png', './img/perfil/banner_default.png', 0, 1),
    (27, 'Autor27', 'autor27@example.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '', '', 0, 1);

    -- Create publicacion table
    CREATE TABLE `publicacion` (
      `id` int NOT NULL AUTO_INCREMENT,
      `id_autor` int NOT NULL,
      `nombre` varchar(200) NOT NULL,
      `titulo` varchar(200) NOT NULL,
      `descripcion` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      `archivo` varchar(200) NOT NULL,
      `imagen_portada` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `idx_publicacion_autor` (`id_autor`),
      CONSTRAINT `fk_publicacion_autor` FOREIGN KEY (`id_autor`) REFERENCES `usuario`(`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Create tag table
    CREATE TABLE `tag` (
      `id` int NOT NULL AUTO_INCREMENT,
      `nombre` varchar(100) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `uk_tag_nombre` (`nombre`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Create publicacion_tag junction table
    CREATE TABLE `publicacion_tag` (
      `publicacion_id` int NOT NULL,
      `tag_id` int NOT NULL,
      PRIMARY KEY (`publicacion_id`, `tag_id`),
      KEY `fk_publicacion_tag_tag` (`tag_id`),
      CONSTRAINT `fk_publicacion_tag_publicacion` FOREIGN KEY (`publicacion_id`) REFERENCES `publicacion` (`id`) ON DELETE CASCADE,
      CONSTRAINT `fk_publicacion_tag_tag` FOREIGN KEY (`tag_id`) REFERENCES `tag` (`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Insert sample tags
    INSERT IGNORE INTO `tag` (`nombre`) VALUES
      ('tecnologia'),
      ('programacion'),
      ('java'),
      ('spring'),
      ('desarrollo'),
      ('web'),
      ('backend'),
      ('frontend'),
      ('docker'),
      ('kubernetes');

    -- Insert sample publicacion
    INSERT IGNORE INTO `publicacion` (`id`, `id_autor`, `nombre`, `titulo`, `descripcion`, `archivo`) VALUES
      (1, 27, 'Pagina azul', 'Pagina azul', 'Pagina azul porque me encanta el azul, azul de mar azul de cielo, azul de pureza. UWU', 'a');

    -- Insert sample publicacion_tag relationships
    INSERT IGNORE INTO `publicacion_tag` (`publicacion_id`, `tag_id`)
    SELECT 1, id FROM `tag` WHERE `nombre` IN ('tecnologia', 'web', 'frontend')
    ON DUPLICATE KEY UPDATE publicacion_id = publicacion_id;

    COMMIT;
